name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build
          npm run export
          touch out/.nojekyll # Ensure GitHub Pages doesn't ignore files starting with an underscore
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add out && git commit -m "Deploy to GitHub Pages" || exit 0
          git subtree split --prefix out -b gh-pages
          git push -f origin gh-pages:gh-pages
